engines:
  - name: google4
    engine: google-4get
    enable_http: true    
    shortcut: g4g  
    categories: general  
    timeout: 5.0  
    disabled: false  
  - name: brave4
    engine: brave-4get 
    enable_http: true   
    shortcut: b4g  
    categories: general  
    timeout: 5.0  
    disabled: false  
    brave_spellcheck: 'yes'
  - name: duckduckgo4
    enable_http: true  
    engine: duckduckgo-4get  
    shortcut: d4g  
    categories: general  
    timeout: 2.0  
    disabled: false
    ddg_extendedsearch: 'yes'
  - name: yandex4
    enable_http: true    
    engine: yandex-4get  
    shortcut: y4g  
    categories: general  
    timeout: 3.0  
    disabled: false
    yandex_language: 'en'
  - name: mojeek4
    engine: mojeek-4get
    enable_http: true
    shortcut: mj4g
    categories: general
    timeout: 2.0
    disabled: false
  - name: yep4
    engine: yep-4get
    enable_http: true
    shortcut: yp4g
    categories: general
    timeout: 2.0
    disabled: false
  - name: marginalia4
    engine: marginalia-4get
    enable_http: true
    shortcut: mg4g
    categories: general
    timeout: 2.0
    disabled: false
    marginalia_intitle: 'no'
  - name: wiby4
    engine: wiby-4get
    enable_http: true
    shortcut: wb4g
    categories: general
    timeout: 2.0
    disabled: false
  - name: curlie4
    engine: curlie-4get
    enable_http: true
    shortcut: cl4g
    categories: general
    timeout: 2.0
    disabled: false
  - name: baidu4
    engine: baidu-4get
    enable_http: true
    shortcut: bd4g
    categories: general
    timeout: 2.0
    disabled: true
  - name: crowdview4
    engine: crowdview-4get
    enable_http: true
    shortcut: cv4g
    categories: general
    timeout: 2.0
    disabled: false